### ISSUE TITLE
Detect scrollbar support

### ISSUE THREAD

**Issue by anteksiler** [ingmarh/scroll-shadow-element#5]
On Windows without any touchpad, the users can't scroll if they do not have a mouse with scroll.

Is there a way to detect and display scrollbars automatically?

**Comment by ingmarh** [comment]
Hi @anteksiler,

In general, `scroll-shadow-element` does not influence scroll bars. It only adds dynamic scroll indicators.

There is no straightforward way to detect and display scroll bars automatically: Whether they are displayed is dependent to the operating system and its scroll bar settings. The appearance of the scroll bars can be controlled in a limited way with CSS. On [the demo page](https://ingmarh.github.io/scroll-shadow-element/demo/), scroll bars were hidden with CSS by default. This might have been confusing and I just removed this behavior of the demo page along with other updates to simplify. So, depending on the device and operating system scroll bar settings, scroll bars might now be displayed on the demo page.

(Independent to the operating system: if users don’t have a touchpad or mouse with scroll bar, they can always use the `Up`/`Down` or `PgUp`/`PgDn` keys of their keyboard to scroll the content after having tabbed into the scrollable area.)
